Repository mattermost/mattermost-plugin-msteams-meetings, pull requests merged in 2022-06, with the labels that each got.

#64 Fix MM-41977
  server/post.go
Labels: 4: Reviews Complete

#63 Added at-rest encryption for the OAuth tokens
  Makefile
  go.mod
  plugin.json
  server/authorization.go
  server/client.go
  server/configuration.go
  server/http.go
  server/meeting.go
  server/plugin.go
  server/post.go
  server/remote/user.go
  server/state.go
  server/store/user.go
  server/user.go
  server/user_test.go
Labels: 2: Dev Review, QA Review Done, Docs/Needed

#74 MM-40214: Add App Bar icon
  Makefile
  public/app-bar-icon.png
  webapp/src/index.tsx
  webapp/src/types/mattermost-webapp/index.d.ts
Labels: 4: Reviews Complete

#76 Bump version to v1.1.0
  go.mod
  go.sum
  plugin.json
  server/manifest.go
Labels: QA Review Done

#75 fixed removing user keys when OAuth2 config changes
  server/configuration.go
  server/user.go
Labels: 4: Reviews Complete, QA Review Done

#77 Bumped to v2.0.0
  plugin.json
  server/manifest.go
Labels: 1: PM Review, 2: Dev Review, QA Review Done
