Repository mattermost/mattermost-plugin-msteams-meetings, pull requests merged in 2024-08, with the labels that each got.

#109 [MM-8]: Added topic for starting meeting
  server/command.go
  server/meeting.go
  server/post.go
  webapp/src/actions/index.ts
  webapp/src/client/client.ts
  webapp/src/components/post_type_mstmeetings/index.ts
  webapp/src/components/post_type_mstmeetings/post_type_mstmeetings.tsx
  webapp/src/index.tsx
Labels: 3: QA Review

#126 [GH-125] Added error logs
  server/http.go
Labels: 3: Security Review

#123 [MM-676]: Fixed issue of meeting link being posted when user successfully connects to MS Teams Meetings
  server/command.go
  server/http.go
  server/state.go
Labels: 4: Reviews Complete, QA Review Done

#130 Bump version number to 2.2.0
  README.md
  plugin.json
  server/manifest.go
  webapp/package-lock.json
Labels: 2: Dev Review
